// @flow
/**
 * A nationality to country code mapping to display driver flags.
 */
export const flags = {
  american: 'us',
  'american-italian': 'us',
  argentine: 'ar',
  'argentine-italian': 'ar',
  australian: 'au',
  austrian: 'at',
  belgian: 'be',
  brazilian: 'br',
  british: 'gb',
  canadian: 'ca',
  chilean: 'cl',
  colombian: 'co',
  czech: 'cz',
  danish: 'dk',
  dutch: 'nl',
  'east german': 'de',
  finnish: 'fi',
  french: 'fr',
  german: 'de',
  hungarian: 'hu',
  indian: 'in',
  indonesian: 'id',
  irish: 'ie',
  italian: 'it',
  japanese: 'jp',
  liechtensteiner: 'li',
  malaysian: 'my',
  mexican: 'mx',
  monegasque: 'mc',
  'new zealander': 'nz',
  polish: 'pl',
  portuguese: 'pt',
  rhodesian: 'zw',
  russian: 'ru',
  'south african': 'za',
  spanish: 'es',
  swedish: 'se',
  swiss: 'ch',
  thai: 'th',
  uruguayan: 'uy',
  venezuelan: 've',
};
